server:
    port: 8080
    error:
        include-message: always
spring:
    datasource:
        url: ${DB_HOST_MYSQL}
        username: ${DB_USERNAME_MYSQL}
        password: ${DB_PASSWORD_MYSQL}
        driver-class-name: com.mysql.cj.jdbc.Driver
    flyway.baseline-on-migrate: true
    jpa:
        hibernate.ddl-auto: validate